spring :
  datasource :
    type : com.alibaba.druid.pool.DruidDataSource
    driver-class-name : com.mysql.jdbc.Driver
#    url : jdbc:mysql://localhost:3306/yulore?characterEncoding=utf8&useSSL=true
#    username : root
#    password : root
    url : jdbc:mysql://bdm2682759.my3w.com:3306/bdm2682759_db?characterEncoding=utf8&useSSL=true
    username : bdm2682759
    password : 12345678
    initialSize : 5
    minIdle : 5
    maxActive : 20
    maxWait : 60000
    timeBetweenEvictionRunsMillis : 60000
    minEvictableIdleTimeMillis : 300000
    validationQuery : SELECT 1 FROM DUAL
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    poolPreparedStatements : true
    maxPoolPreparedStatementPerConnectionSize : 20
    filters : stat,wall
    connectionProperties : druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat : true
server:
  port: 8868
  tomcat:
    uri-encoding: UTF-8
yulore:
  metadata:
    city: https://apis-android.dianhua.cn/city/?sig=862017031927933&uid=862017031927933&apikey=kq49MtFgDyNwuWtBxeyQqzfJhqOyW92k&auth_id=
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl